openapi: 3.0.3
info:
  title: Activity Service API
  description: API for managing user activity sessions
  version: 1.0.0
  contact:
    name: Activity Service Team

servers:
  - url: http://localhost:8083
    description: Local development server

tags:
  - name: Session Management
    description: Operations related to activity session management

paths:
  /session:
    post:
      tags:
        - Session Management
      summary: Create a new session
      description: Creates a new activity session
      operationId: createSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        '200':
          description: Session created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

    get:
      tags:
        - Session Management
      summary: Get all sessions
      description: Retrieves a list of all activity sessions
      operationId: getAllSessions
      responses:
        '200':
          description: Sessions retrieved successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Session'
        '500':
          description: Internal server error

  /session/{id}:
    get:
      tags:
        - Session Management
      summary: Get session by ID
      description: Retrieves a specific session by its ID
      operationId: getSessionById
      parameters:
        - name: id
          in: path
          required: true
          description: Session ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Session retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Session not found
        '500':
          description: Internal server error

    put:
      tags:
        - Session Management
      summary: Update session
      description: Updates an existing activity session
      operationId: updateSession
      parameters:
        - name: id
          in: path
          required: true
          description: Session ID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        '200':
          description: Session updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Session not found
        '400':
          description: Invalid input
        '500':
          description: Internal server error

    delete:
      tags:
        - Session Management
      summary: Delete session
      description: Deletes an activity session
      operationId: deleteSession
      parameters:
        - name: id
          in: path
          required: true
          description: Session ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Session deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Session not found
        '500':
          description: Internal server error

components:
  schemas:
    Session:
      type: object
      required:
        - userId
        - type
      properties:
        id:
          type: integer
          format: int64
          description: Session ID
        createdAt:
          type: string
          format: date-time
          description: Session creation timestamp
        userId:
          type: integer
          format: int64
          description: ID of the user who owns this session
        type:
          type: string
          enum:
            - RUNNING
            - CYCLING
            - WALKING
          description: Type of activity session
        prompt:
          type: string
          description: Optional prompt or description for the session
          nullable: true

    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the operation was successful
        message:
          type: string
          description: Response message
        data:
          type: object
          description: Response data
